### PR TITLE
IA Wiki Overhaul | Better For First Time Users 

### PR DESCRIPTION
**Pull request by thefourcraft**
<div align="center"><h1 >PLEASE DON'T COMMIT ANY CHANGES<br>
THAT WILL BRAKE MY FIX<h1><h2>Thanks thefourCraft</h2></div>

# The New Old Wiki 🆕
This Wiki update attempts to help new users to understand the plugin and get them on board
Basically to shorten the learning curve, and improve the accuracy of information
This update comprises suggestions and general feedback from the discord server or the spigotMC reviews
## What Are The New Changes 📐
- The All New Home Page
I wanted to put the important links in front of new users, and point them in the right direction when starting out
That's why the front page has more links and other improvements
- Added Partners To Wiki
- Added Slang Doc
- Improved Old Wiki Pages
- Fixed Some Typos
- First Installation Fixing (again)
Yes, People Still Make Mistakes... So we need to improve and clarify things 
- Cleared Up Nav Bar
- Fixing the merging issues https://github.com/thefourcraft/Wiki-ItemsAdder/pull/1
- This is the updated branch, now it should work... https://github.com/LoneDev6/Wiki-ItemsAdder/pull/58#issue-1431994282
- Fixed Old Guides Pages
- Better More Accurate First Installation Page
- Added Partners to the wiki and a new partner policy
- Added A new guide for contributors
- Moved Things and fixed sections on the main wiki side navigation panel
- Improved First Install Page
- ~4000+ Typos Fixed
- Merging Issues Fix From https://github.com/thefourcraft/Wiki-ItemsAdder/pull/6
- Fixed Meggsing Issue From GitBook Update https://github.com/thefourcraft/Wiki-ItemsAdder/pull/5
***
Had To Fix All the conflicts manually....

### CODE REVIEW

**Comment by LoneDev6** [comment]
Can you please work on the wiki after you got the most recent wiki changes?
You always work on outdated wiki pages..
I cannot merge this.

Examples:

image

image

Delete your wiki contents and start with the current official most up to date one. It's impossible for me to have to manually fix each of your commits.

Thanks

**Comment by thefourcraft** [comment]
its the most up-to-date, and It works on Gitbook, I changed it from the markdown to HTML but it still works
Gitbook understands HTML you just have to insert it manually

I tested out the compatibility with the currently most updated branch no issues

**Comment by LoneDev6** [comment]
No no I mean, the image file names in your commits are strange, check the left part of the screenshots I sent

**Comment by thefourcraft** [comment]
> No no I mean, the image file names in your commits are strange, check the left part of the screenshots I sent

I will check it out, don't close the PR... leave it open I will be able to repair the commits and take a second look...

My last commit to my repo was from Gitbook and it might messed things up 🤬😡

**Comment by LoneDev6** [comment]
You should manually edit files and not use Gitbook to do that. I assume that you imported the repository on your own Gitbook account, this surely causes issues.

Avoid doing that, manually edit using visualstudio code to avoid such issues.

**Pull request closed without merging**
