### PR TITLE
Updating Information ℹ

### PR DESCRIPTION
**Pull request by thefourcraft**
## New Category
image
## Fixed Bungeecord pages 
image
## More
- Fixed An Issue on the first Installation page
- Added FAQ about the IA golden rule
- Fixed My Typos on some pages 🤫
- Added How to use Gitbook 

Hopefully, Gitbook didn't change any other random things

### CODE REVIEW

**Comment by LoneDev6** [comment]
Thanks for the help, but I have one question.
Why did you remove some emojis from page names?

image

**Comment by thefourcraft** [comment]
It's interesting, I fixed it

**Comment by thefourcraft** [comment]
the conflicts are a result of Gitbook being stupid and removing things

**Comment by thefourcraft** [comment]
> I also noticed a lot of new images, are they correct? https://github.com/LoneDev6/Wiki-ItemsAdder/pull/58/files#diff-88cb62d0e1ee3b2e2a4b198e0d25648059cf908b12965828d76bc030cdd11a2f

I think that It's Gitbook removing the `../../..` because we have a lot of photos #60 
not sure what happened, and why it like so on my pulls
on my wiki it looks like nothing has changed I went and checked all the pages related


## Here Are The Changes And Screenshots From My GitBook
plugin-usage/scoreboard/hide-scoreboard-numbers-1.17+.md
image
faq/identify-why-textures-are-not-shown.md
image
contributing/contribute/translate-this-wiki.md
image


# NOT SURE WHY GITBOOK ADDING `././././././././`
I guess its a bug, or something on their side 👐

**Comment by LoneDev6** [comment]
`/../` means that the image is 1 folder up the current .md file directory, basically.
This is what this special notation is used.

**Comment by thefourcraft** [comment]
> `/../` means that the image is 1 folder up from the current .md file directory, basically. This is why this special notation is used.

I will make other pushes to fix the issue with the conflicts, and maybe change my repository also
its an issue with the synchronization  between Gitbook and GitHub

very interesting

**Pull request closed without merging**
